import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.scss";
import TopAppBar from "@/components/TopAppBar/TopAppBar";

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>{/* Include your meta tags, title, stylesheets, etc. here */}</head>
      <body className={inter.className}>
        <TopAppBar />
        <main>{children}</main>
      </body>
    </html>
  );
}
