# Generated by Django 5.0 on 2023-12-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
