# Generated by Django 5.0 on 2023-12-09 15:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="description",
        ),
    ]
