# Generated by Django 5.0 on 2023-12-09 15:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_remove_image_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="file",
        ),
    ]
