# Generated by Django 5.0 on 2023-12-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_image_image_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="file",
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.FileField(default="", upload_to="thoughts"),
        ),
    ]
