# Generated by Django 5.0 on 2023-12-09 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_remove_image_file_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="file",
        ),
    ]
