# Generated by Django 5.0 on 2023-12-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_rename_image_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image_cover",
            field=models.FileField(default="", upload_to="thoughts"),
        ),
    ]
